In [3]:
from sklearn.datasets import load_iris
from sklearn.naive_bayes import GaussianNB
from sklearn.metrics import confusion_matrix, accuracy_score, precision_score, recall_score, f1_score
from sklearn.metrics import roc_curve, roc_auc_score
from sklearn.model_selection import train_test_split

iris = load_iris()
X = iris.data
y = iris.target

X_train , X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=122)

In [4]:
gnb_clf = GaussianNB()
gnb_clf.fit(X_train, y_train)
pred = gnb_clf.predict(X_test)
pred_proba = gnb_clf.predict_proba(X_test)

In [5]:
result = confusion_matrix(y_test, pred)
result

array([[ 8,  0,  0],
       [ 0, 10,  1],
       [ 0,  0, 11]], dtype=int64)

In [6]:
accuracy_score(y_test, pred)

0.9666666666666667

precision_score(y_test, pred, average='micro')

In [7]:
recall_score(y_test, pred, average='micro')

0.9666666666666667

In [8]:
f1_score(y_test, pred, average='micro')

0.9666666666666667

# sklearn.naive_bayes.MultinomialNB(다항분포모델)
### class sklearn.naive_bayes.MultinomialNB(*, alpha=1.0, force_alpha=True, fit_prior=True, class_prior=None)

In [14]:
import numpy as np
import random

random.seed(42)
x=np.random.randint(5, size=(7,100))
y=np.array([1,2,3,4,5,6,7])

In [15]:
from sklearn.naive_bayes import MultinomialNB

mlnb_clf=MultinomialNB()
mlnb_clf.fit(x,y)
x_test=np.array([3, 1, 4, 0, 4, 4, 0, 0, 4, 2, 2, 2, 1, 2, 2, 1, 1, 0, 0, 1, 3, 0,
        4, 3, 4, 4, 3, 3, 1, 0, 2, 1, 3, 0, 0, 2, 0, 4, 1, 2, 1, 3, 3, 2,
        3, 3, 1, 2, 4, 3, 1, 3, 4, 1, 1, 3, 2, 3, 2, 3, 2, 1, 3, 2, 0, 1,
        2, 0, 0, 4, 3, 2, 3, 4, 1, 1, 3, 3, 2, 2, 2, 2, 1, 4, 2, 3, 1, 1,
        1, 1, 4, 2, 3, 1, 2, 2, 4, 2, 1, 3]).reshape(1,-1)

mlnb_clf.predict(x_test)

array([5])

In [12]:
x

array([[3, 1, 4, 0, 4, 4, 0, 0, 4, 2, 2, 2, 1, 2, 2, 1, 1, 0, 0, 1, 3, 0,
        4, 3, 4, 4, 3, 3, 1, 0, 2, 1, 3, 0, 0, 2, 0, 4, 1, 2, 1, 3, 3, 2,
        3, 3, 1, 2, 4, 3, 1, 3, 4, 1, 1, 3, 2, 3, 2, 3, 2, 1, 3, 2, 0, 1,
        2, 0, 0, 4, 3, 2, 3, 4, 1, 1, 3, 3, 2, 2, 2, 2, 1, 4, 2, 3, 1, 1,
        1, 1, 4, 2, 3, 1, 2, 2, 4, 2, 1, 3],
       [3, 1, 2, 0, 0, 2, 4, 3, 0, 0, 1, 0, 0, 1, 1, 1, 3, 3, 2, 1, 2, 0,
        2, 0, 2, 3, 2, 1, 1, 0, 3, 0, 3, 0, 1, 2, 4, 2, 2, 0, 2, 0, 2, 0,
        3, 4, 3, 2, 0, 0, 0, 3, 3, 4, 1, 2, 0, 3, 4, 0, 0, 4, 0, 2, 3, 2,
        2, 3, 4, 4, 3, 0, 1, 4, 2, 4, 1, 1, 1, 3, 0, 2, 3, 3, 3, 1, 4, 0,
        1, 1, 0, 3, 2, 2, 2, 2, 4, 0, 4, 3],
       [4, 4, 1, 1, 3, 1, 4, 1, 0, 3, 1, 4, 0, 4, 2, 3, 1, 0, 0, 2, 0, 3,
        0, 4, 4, 2, 1, 2, 1, 2, 4, 4, 1, 1, 1, 1, 1, 3, 4, 0, 3, 0, 2, 0,
        2, 3, 4, 3, 3, 4, 4, 3, 3, 0, 1, 3, 2, 2, 1, 0, 2, 3, 4, 2, 4, 3,
        1, 2, 4, 2, 4, 3, 3, 2, 0, 4, 3, 2, 1, 0, 1, 1, 1, 3, 2, 0, 0, 4,
        2, 3, 3, 4, 1,